        !COMPILER-GENERATED INTERFACE MODULE: Sun Jul 22 18:55:53 2018
        MODULE OBJFUNC__genmod
          INTERFACE 
            SUBROUTINE OBJFUNC(NPAR,NSIM,X,R,F,ERROR,MESSAGE)
              INTEGER(KIND=8), INTENT(IN) :: NPAR
              INTEGER(KIND=8), INTENT(IN) :: NSIM
              REAL(KIND=8), INTENT(IN) :: X(:)
              REAL(KIND=8), INTENT(OUT) :: R(:)
              REAL(KIND=8), INTENT(OUT) :: F
              INTEGER(KIND=8), INTENT(OUT) :: ERROR
              CHARACTER(LEN=100), INTENT(OUT) :: MESSAGE
            END SUBROUTINE OBJFUNC
          END INTERFACE 
        END MODULE OBJFUNC__genmod
